---
- name: reload-user-systemd
  ansible.builtin.command: systemctl --user daemon-reload
  become: true
  become_user: "{{ solstream_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ lookup('pipe', 'id -u ' + solstream_user) }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ lookup('pipe', 'id -u ' + solstream_user) }}/bus"
  changed_when: false
