# SolStream is unfunded right now. If you'd like to sponsor the project,
# add a value below and uncomment the relevant line.

# github: [mxmjxn]
# ko_fi: solstream
# custom: ["https://yourdomain.com/donate"]
